services:
  db:
    container_name: db
    image: "mongo:${MONGODB_VERSION}"
    command: "mongod --bind_ip 0.0.0.0 --port 27017"
    networks:
      open5gs:
        aliases:
          - db.open5gs.org
    volumes:
      - db_data:/data/db
      - db_config:/data/configdb
    ports:
      - "0.0.0.0:27017:27017/tcp"

  nrf:
    container_name: nrf
    image: "ghcr.io/borjis131/nrf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/nrf.yaml"
    networks:
      open5gs:
        aliases:
          - nrf.open5gs.org
    configs:
      - source: nrf_config
        target: /etc/open5gs/custom/nrf.yaml

  ausf:
    container_name: ausf
    image: "ghcr.io/borjis131/ausf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/ausf.yaml"
    networks:
      open5gs:
        aliases:
          - ausf.open5gs.org
    configs:
      - source: ausf_config
        target: /etc/open5gs/custom/ausf.yaml
    depends_on:
      - nrf

  udm:
    container_name: udm
    image: "ghcr.io/borjis131/udm:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/udm.yaml"
    networks:
      open5gs:
        aliases:
          - udm.open5gs.org
    configs:
      - source: udm_config
        target: /etc/open5gs/custom/udm.yaml
    depends_on:
      - nrf

  udr:
    container_name: udr
    image: "ghcr.io/borjis131/udr:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/udr.yaml"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - udr.open5gs.org
    configs:
      - source: udr_config
        target: /etc/open5gs/custom/udr.yaml
    depends_on:
      - db
      - nrf

  nssf:
    container_name: nssf
    image: "ghcr.io/borjis131/nssf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/nssf.yaml"
    networks:
      open5gs:
        aliases:
          - nssf.open5gs.org
    configs:
      - source: nssf_config
        target: /etc/open5gs/custom/nssf.yaml
    depends_on:
      - nrf

  bsf:
    container_name: bsf
    image: "ghcr.io/borjis131/bsf:${OPEN5GS_VERSION}"
    command: "-c /open5gs/config/bsf.yaml"
    networks:
      open5gs:
        aliases:
          - bsf.open5gs.org
    configs:
      - source: bsf_config
        target: /open5gs/config/bsf.yaml
    depends_on:
      - nrf

  pcf:
    container_name: pcf
    image: "ghcr.io/borjis131/pcf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/pcf.yaml"
    restart: unless-stopped
    networks:
      open5gs:
        aliases:
          - pcf.open5gs.org
    configs:
      - source: pcf_config
        target: /etc/open5gs/custom/pcf.yaml
    depends_on:
      - db
      - nrf

  amf:
    container_name: amf
    image: "ghcr.io/borjis131/amf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/amf.yaml"
    networks:
      open5gs:
        aliases:
          - amf.open5gs.org
    configs:
      - source: amf_config
        target: /etc/open5gs/custom/amf.yaml
    depends_on:
      - nrf
    ports:
      - "0.0.0.0:38412:38412/sctp"

  mb-smf:
    container_name: mb-smf
    image: "mb-smf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/mb-smf.yaml"
    networks:
      open5gs:
        aliases:
          - mb-smf.open5gs.org
    configs:
      - source: mb_smf_config
        target: /etc/open5gs/custom/mb-smf.yaml
    depends_on:
      - nrf
      - mb-upf

  mb-upf:
    container_name: mb-upf
    image: "mb-upf:${OPEN5GS_VERSION}"
    command: "-c /etc/open5gs/custom/mb-upf.yaml"
    networks:
      open5gs:
        aliases:
          - mb-upf.open5gs.org
    extra_hosts:
      docker-host.external-ip: 172.33.33.33
    configs:
      - source: mb_upf_config
        target: /etc/open5gs/custom/mb-upf.yaml
    ports:
      - "0.0.0.0:2152:2152/udp"
    privileged: true
    cap_add:
      - NET_ADMIN

  af:
    container_name: af
    image: "af:${OPEN5GS_VERSION}"
    networks:
      open5gs:
        aliases:
          - af.open5gs.org
    volumes:
      - ./test:/test:ro

networks:
  open5gs:
    name: open5gs
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-ogs
    ipam:
      config:
        - subnet: 10.33.33.0/24

volumes:
  db_data:
    name: open5gs_db_data
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}
  db_config:
    name: open5gs_db_config
    labels:
      org.open5gs.mongodb_version: ${MONGODB_VERSION}

configs:
  nrf_config:
    file: configs/nrf.yaml
  ausf_config:
    file: configs/ausf.yaml
  udm_config:
    file: configs/udm.yaml
  udr_config:
    file: configs/udr.yaml
  nssf_config:
    file: configs/nssf.yaml
  bsf_config:
    file: configs/bsf.yaml
  pcf_config:
    file: configs/pcf.yaml
  amf_config:
    file: configs/amf.yaml
  mb_smf_config:
    file: configs/mb-smf.yaml
  mb_upf_config:
    file: configs/mb-upf.yaml
